### ISSUE TITLE
Constructor SimpleFragmentPagerAdapter couldn't be resolved

### ISSUE THREAD

**Issue by shrynshigupta06** [udacity/ud839_ViewPager_Example#1]

**Comment by arp-wtm** [comment]
i had the same problem. I resolved with update to build.gradle : buildToolsVersion '23.0.2' and compile 'com.android.support:appcompat-v7:23.2.1' 
this is the link to the file https://github.com/udacity/ud839_ViewPager_Example/blob/master/app/build.gradle

**Comment by s1x8** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.example.android.viewpager"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:27.1.1'
}

**Comment by ghost** [comment]
Still not working for me. I'm getting the following error after attempting the above recommended fix: 

Error:(1, 1) A problem occurred evaluating root project 'ud839_ViewPager_Example-quiz'.
> Plugin with id 'com.android.application' not found.

**Comment by arp-wtm** [comment]
@alanionita control also the file **build.gradle** (Project: ud839_ViewPager_Example)

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by ghost** [comment]
@arp-wtm Thanks for the snippet, that worked for me! 🙌

**Comment by arp-wtm** [comment]
You can  learn more with this free course: [Gradle for Android and Java](https://eu.udacity.com/course/gradle-for-android-and-java--ud867)

**Comment by SudKul** [comment]
We have upgraded the repo to AndroidX in a recent [commit](https://github.com/udacity/ud839_ViewPager_Example/commit/60bc07c95843e4ca74f67e066a798a2ab16d8f2f). 

For further issues, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
