### ISSUE TITLE
Could not run build action using Gradle distribution

### ISSUE THREAD

**Issue by anuragsingh23** [udacity/ud839_ViewPager_Example#10]
12:50 AM	Gradle sync started

12:50 AM	Gradle sync failed: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.10-all.zip'.
					Consult IDE log for more details (Help | Show Log) (131 ms)

**Comment by SudKul** [comment]
We have fixed the repo in a recent [commit](https://github.com/udacity/ud839_ViewPager_Example/commit/60bc07c95843e4ca74f67e066a798a2ab16d8f2f). 

For further issues, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
