### ISSUE TITLE
I cant find Fragment name on top rest all works good

### ISSUE THREAD

**Issue by vrush96** [udacity/ud839_ViewPager_Example#2]
I cant find the names of fragment on top rest all data is coming good

**Comment by xMagicXs** [comment]
replace that line of code in imports after u create the new classes
import android.support.app.Fragment;    with   import android.support.v4.app.Fragment;
in both ThursdayFragment class and FridayFragment class and the simplepagerfragmentadaptor will
find your fragments

**Comment by SudKul** [comment]
Closing the stale issues.
