### ISSUE TITLE
MainActivity not able to call viewpager

### ISSUE THREAD

**Issue by surajsahani** [udacity/ud839_ViewPager_Example#9]
_Ambiguous method call. Both
findViewById
(int)
in AppCompatActivity and
findViewById
(int)
in Activity match_

**Comment by SudKul** [comment]
We have fixed the repo in a recent [commit](https://github.com/udacity/ud839_ViewPager_Example/commit/60bc07c95843e4ca74f67e066a798a2ab16d8f2f).
